from collections.abc import Iterator, Mapping
from typing import Protocol

import pandas as pd


class WorkbookReader(Protocol):
    def sheet_names(self, path: str, password: str | None = None) -> list[str]: ...
    def read_sheet(self, path: str, sheet: str | int, password: str | None = None) -> pd.DataFrame: ...
    def read_workbook(self, path: str, password: str | None = None) -> Mapping[str, pd.DataFrame]: ...
    def iter_files(self, root: str, glob: str | None, recursive: bool) -> Iterator[str]: ...
