from typing import Mapping, Protocol
import pandas as pd

class WorkbookWriter(Protocol):
    def write_single_sheet(self, df: pd.DataFrame, out_path: str, sheet_name: str = "Data") -> None: ...
    def write_multi_sheets(self, mapping: Mapping[str, pd.DataFrame], out_path: str) -> None: ...
