from typing import ContextManager, Mapping, Protocol

import pandas as pd


class SheetStream(Protocol):
    def append(self, df: pd.DataFrame) -> None: ...


class WorkbookWriter(Protocol):
    def write_single_sheet(self, df: pd.DataFrame, out_path: str, sheet_name: str = "Data") -> None: ...
    def write_multi_sheets(self, mapping: Mapping[str, pd.DataFrame], out_path: str) -> None: ...
    def stream_single_sheet(self, out_path: str, sheet_name: str = "Data") -> ContextManager[SheetStream]: ...
